url: http://biorefine.bluetree.jp
#baseurl: /agency-jekyll-theme/

# Site settings
title: biorefine
year: 2016
email: biorefine@bluetree.jp
description: "publication translation and proofreading"
objective: "Let us take care of your proofreading or translation!"
detail: "We can guarantee your publication will be in native English and provide support for you until it is complete."

service0: Start
service1detail: Start by submitting your document now!
service1: Workflow 
service1detail: Our efficient workflow shows how we are always complete and on time.
service2: Translation
service2detail: Translation services range from a variety of formats.
service3: Proofreading
service3detail: Our proofreading is specialized in the bio-informatical field.
service4: Support
service4detail: Support for your paper will be available from first upload to publication.

motto: native english, native support
getstarted: If you have a document ready, we can scan it and quote a price, or you can simply check our pricing table.
permalink: date

paginate: 4
paginate_path: /blog/page:num/

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 005CE6
  #primary: 4242ef
  #secondary: 2E2EA7
  secondary: 004AB8
  secondary-dark: FFF

# Team names, titles and social links
people:
- name: refine
  pic: 1
  position: 
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/aokinobu
  - title: facebook
    url: http://facebook.com/aokinobu
  - title: rss
    url: /rss.xml
  - title: bitbucket 
    url: http://bitbucket.org/aokinobu
  - title: github
    url: http://github.com/aokinobu

# Postal address (add as many lines as necessary)
address:
  - line: 1234 Blue Tree Lane
  - line: Ibaragi, Japan

# Build settings
markdown: kramdown

gems: [jekyll-paginate]
