url: http://refine.bluetree.jp
#baseurl: /agency-jekyll-theme/

# Site settings
title: refine
year: 2015
email: refine@bluetree.jp
description: "publication translation and proofreading"
objective: "Leave the proofreading or translation of your publication to us!"
detail: "We can guarantee your publication will in native English and provide complete support for you until it is ready."

service1: translation
service2: proofreading
service3: support
service4: speed

motto: native english speakers at your service
getstarted: If you have a document ready, we can scan it and quote a price, or just check our pricing table.
permalink: date

paginate: 4
paginate_path: /blog/page:num/

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 005CE6
  #primary: 4242ef
  #secondary: 2E2EA7
  secondary: 004AB8
  secondary-dark: FFF

# Team names, titles and social links
people:
- name: refine
  pic: 1
  position: 
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/aokinobu
  - title: facebook
    url: http://facebook.com/aokinobu
  - title: rss
    url: /rss.xml
  - title: bitbucket 
    url: http://bitbucket.org/aokinobu
  - title: github
    url: http://github.com/aokinobu

# Postal address (add as many lines as necessary)
address:
  - line: 1234 Blue Tree Lane
  - line: Ibaragi, Japan

# Build settings
markdown: kramdown

gems: [jekyll-paginate]
